### ISSUE TITLE
Print Images / PDFs

### ISSUE THREAD

**Issue by ttisch** [InteractiveObject/StarIOPlugin#14]
As I found no way to print PDFs directly, my question is if there's an easy way to print images with this plugin? Are there any functions already or do I have to add native .java files and "extend" the cordova plugin with the functionality?

I discovered there is a native method in the StarIO SDK: ```PrintBitmapImage(Context context, String portName, String portSettings, Resources res, int source, int maxWidth, boolean compressionEnable, RasterCommand rasterType)```

Thanks for any help!!

**Comment by martinkonzettpalisis** [comment]
I have a similar need in my app using the StarIOPlugin to print bitmap images as well as QR codes. Is there any news on this?

Thanks

**Comment by envisiondata** [comment]
Do you know any native programming? If so look at the SDK from StarIO it has an example. You can find on their website. 

I used the example code they provided and changed as needed. Most of the classes come straight from the example code. I just imported them into my project. You will need to do the same. 

James
