### ISSUE TITLE
iOS Build error

### ISSUE THREAD

**Issue by mba858** [InteractiveObject/StarIOPlugin#4]
We'r getting this error while building for iOS.
 fatal error: 'StarIO/SMPort.h' file not found
# import <StarIO/SMPort.h>

Please suggest some help or other solution to resolve it.
Thanks

**Comment by warbadev** [comment]
i got the same error also really need a solution asap i did add all stario.framwork and did edit the plugin.xml but still cant build

**Comment by geo242** [comment]
@mba858 @warbadev I have noticed this is a pretty common issue when dealing with 3rd party frameworks. Typically the solution lies in making sure the search path in xcode includes where the framework files are. I hope that helps.

**Comment by warbadev** [comment]
@geo242 thanks man i didnt try before to work with xcode it was only cordova stuff u saved me today and taught  me something new
... do u know how to print the logo in mpop?

**Comment by jasonfutch** [comment]
Having same issue can you clarify the fix?

**Comment by Rcjuk** [comment]
@younes200 Can confirm I get the same issue

**Comment by safanmomin** [comment]
@warbadev can you please post details about how you solved the issue?

**Comment by ttisch** [comment]
@safanmomin I too got it to working by adding StarIO and StarIO_Extension Frameworks to "Build Phases Tab" in xCode and enabling the "Copy files if needed" checkbox.
