### ISSUE TITLE
No visible @interface for 'PortInfo'

### ISSUE THREAD

**Issue by auctifera-josed** [InteractiveObject/StarIOPlugin#5]
After adding, the plugin and following star guide to add frameworks to the project I get the following error

> no visible @interface for 'PortInfo' declares the selector 'isConnected'

I got this error using both ios 3.9.2 and 4.*, andy idea what I did wrong?

**Comment by warbadev** [comment]
at last i get it figured to import the framework but now i faced this problem  spent the last 48 hours working on this and no result really need a solution please help

**Comment by warbadev** [comment]
solved it at last just remove ios platform then add it while u have the plugin then add the framworks and it will run

but man the owner need to update the demo :)

**Comment by auctifera-josed** [comment]
I actually got this working by only adding StarIO.framework and StarIO_Extension.framework and not adding the SMCloudServices.framework and also commenting out the line `[dict setObject:[NSNumber numberWithBool:[portInfo isConnected]] forKey:@"isConnected"];` in the `portInfoToDictionary`

**Comment by warbadev** [comment]
@auctifera-josed well then since u have been using this long time before me can i ask u how to print the logo ?? am used to do it in epson printer by configuring the printer to print the logo after every cut but here i dont know where to do it... i know its out of the subject but really need to do it and am desperate 
thanks

**Comment by auctifera-josed** [comment]
Hi @warbadev, haven't get around to use images yet (if that's what you mean by 'logo') but probably will soon, you can check my [plugin](https://github.com/auctifera-josed/starprnt)

**Comment by warbadev** [comment]
@auctifera-josedi checked it looks fine but still my problem is there no support to print the logo there pls if u can do it asap u will be my savior 😊
