### ISSUE TITLE
printReceipt callback does not work

### ISSUE THREAD

**Issue by Saulf1** [InteractiveObject/StarIOPlugin#8]
The printReceipt function does not seem to return anything in the callback. An example of my code is shown below, none of the console.log's are triggered even though the receipt has printed successfully. 

`window.plugins.starPrinter.printReceipt(printer, receipt, function(error, result) {
console.log('callback');
                    if (error) {
                      console.error(error);
                    } else {
                      console.log("printReceipt finished");
                    }
                  });`

**Comment by younes200** [comment]
Hi @Saulf1,
Are you using iOS or Android device ?
/Y

**Comment by Saulf1** [comment]
Hi @younes200,

I've only tested this on an Android device so far but I do plan to be using it with iOS as well.

**Comment by Rcjuk** [comment]
Hey @younes200. Thanks for your work. Any update on this?

**Comment by sourcer18** [comment]
@younes200  The same thing happens to me, I do not receive a response from the print, why does it happen? I can find the name, and it appears connected to the printer. Should I add the sdk to the project ?, How is it done ?, I have not added the sdk to the project

**Comment by offlineprogrammer** [comment]
I am getting the same issue on Android with a LAN printer

**Comment by sourcer18** [comment]
@offlineprogrammer In my case, I want to connect to a printer by bluetooth, are you trying to add sdk?

**Comment by sourcer18** [comment]
@offlineprogrammer In my case, I want to connect to a printer by bluetooth, are you trying to add sdk?

**Comment by offlineprogrammer** [comment]
@sourcer18 I am working on ionic2 App...I have the sdk in the lib folder....I can get printer name and macAddress...but the printReceipt function is not doing anything

**Comment by sourcer18** [comment]
offlineprogrammer  The same thing happens to me

**Comment by offlineprogrammer** [comment]
@younes200 any thoughts on this please
